
all:
	g++ iotest.cpp -o iotest
	g++ camera.cpp cameratest.cpp point.cpp matrix.cpp superquadric.cpp -o cameratest

iotest:
	g++ iotest.cpp -o iotest

raytrace:
	g++ camera.cpp cameratest.cpp point.cpp matrix.cpp superquadric.cpp -o cameratest

clean:
	rm -f *.o cameratest iotest